#!/bin/bash

token="578753873:AAEuDKFXMEVY9SoLLdMBpeOY0gN18dQWcPg"

GetUpdate(){
	json=""
	ok=""
	result=""
	while [ "$ok" != "true" ] || [ "$result" = "null" ]
	do
		json=$(curl --progress-bar "https://api.telegram.org/bot$token/getUpdates" -d limit=1 -d timeout=30)
		ok=$(printf "$json" | jq -r .ok)
		result=$(printf "$json" | jq -r .result[0])
	done
	update_id=$( printf "$json" | jq -r .result[0].update_id )
}

ClearUpdate(){
	ok=""
	while [ "$ok" != "true" ]
	do
		ok=$(curl -s "https://api.telegram.org/bot$token/getUpdates" -d offset=$(($update_id+1)) -d limit=1 | jq -r .ok)
	done
}

while true
do
	GetUpdate
	ClearUpdate
done
